{{- if .Values.server.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "monstera.server.fullname" . }}
  labels:
    {{- include "monstera.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.server.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.server.ingress.className }}
  ingressClassName: {{ .Values.server.ingress.className | quote }}
  {{- end }}
  {{- with .Values.server.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.server.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "monstera.server.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
