apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monstera.ui.fullname" . }}-config
  labels:
    {{- include "monstera.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
data:
  config.json: |
    {
      "server_url": {{ .Values.ui.config.server_url | quote }},
      "auth_client_id": {{ .Values.ui.config.auth_client_id | quote }},
      "auth_scopes": {{ .Values.ui.config.auth_scopes | quote }}
    }
